wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    huggingface_version: 4.1.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.1
